baseURL = "https://alexwnovak.github.io/"
languageCode = "en-us"
title = "Brainspace"
theme = "vienna"

[params]
author = "Alex Novak"
avatar = "/images/avatar.jpg"
bio = "Alex Novak is a seasoned .NET guy who chases quality through automated testing. Reach him at @alexwnovak for questions and comments."
twitter = "alexwnovak"
github = "alexwnovak"
subtitle = "Let's talk about development"
themecolor = "#89995d"
